# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-29 23:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0002_auto_20160330_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Category'),
        ),
    ]
