# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 03:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('debate', '0003_auto_20160330_0845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='parent_agenda',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Agenda'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='debate.Category'),
        ),
    ]
